### ISSUE TITLE
verify "dumps" run effectively on P4

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#103]
Production has nightly and weekly dump functions that, I believe, are fired by cron jobs that startup a separate, scripted instance to accomplish the export. We should make sure that these scripted instances run properly to completion, and produce the expected output, on P4 before deploying to production. We should also verify that ansible steps (or some other deployment mechanism) are in place to ensure we get the desired behavior on production after deploy.

**Comment by alecpm** [comment]
These should be available in ``/var/www/atlantides.org/downloads/pleiades/``, we don't yet have a complete RDF export, but the kml and csv exports appear to be working, along with the daily sitemap export. These are not currently available through the web, since they live under the atlantides.org virtual host.

When testing the dumps, I ran across a couple bugs. One was a simple backwards incompatible import in the dump script, but the other was a little more worrisome. In the KML export, a call to:

    unicode(b.getNameAttested, 'utf-8')

In the lookup of ``appellations`` raising an error because the attested name was sometimes missing a value (``coercing to Unicode: need string or buffer, NoneType found``). Replacing that with:

    unicode(b.getNameAttested or "None", 'utf-8')

Allowed the export to complete, but this may be a case where there's a deeper underlying issue if we expect there to always be an attested name for every ``Name`` object. It's may be a good idea to compare exports between live and staging to see if there's a meaningful difference here.

**Comment by paregorios** [comment]
It's not clear how to me to get to these to view/test on staging.

**Comment by alecpm** [comment]
You should be able to SSH to the pleiades.jazkarta.com server using the same login and SSH key you use for atlantides.org and download the files from there. Alternatively, we could set up a domain alias so you could view those files through the web server.

**Comment by paregorios** [comment]
ssh is fine; I'll use that method. Thanks.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
regarding ssh: Permission denied (publickey), but I can still use that key to login to atlantides.org. :(

**Comment by alecpm** [comment]
Is this for the 16.04 or 14.04 server? I don't think I had run the user playbook on the 16.04 server. I've re-run it on both servers now. Could you try again?

**Comment by paregorios** [comment]
looks like a derelict public key got picked up for the ansible script; pull request above replaces it with a known good one.

**Comment by alecpm** [comment]
OK, public keys have been updated on both servers.

**Comment by paregorios** [comment]
I'm able to login now, thanks.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
CSV dumps on the 16.04 server under ```/var/www/atlantides.org/downloads/pleiades/dumps``` appear to only contain a few bytes of garbage.

**Comment by paregorios** [comment]
KML export on the other hand, looks healthy on a macro level. It's a big, valid KMZ file and it paints the picture I expect to see in Google Earth. I will need to dig into particulars before giving it a clean bill of health.

**Comment by paregorios** [comment]
RDF exports, like the CSV exports, are all small or zero-length files.

**Comment by alecpm** [comment]
I haven't checked the dump setup on 16.04, I'll do that now. Do CSV and RDF look OK on 14.04?

**Comment by alecpm** [comment]
It looks like there was a strange issue with the way the dump script was interpreting command line arguments on 16.04. I've fixed that issue and am re-running the dumps.

**Comment by paregorios** [comment]
We still have problems (I'm looking at content on 52.38.6.139). Some more of the files appear superficially complete, but we are still missing content from the following:

- locations CSV files (in ```dumps/```)
- names CSV files (in ```dumps/```)

These files no longer contain garbage, and they do contain the expected column headers, but there are no data rows.

There are no files at all in ```rdf/```, so I guess that dump hasn't been re-run?

**Comment by alecpm** [comment]
OK, something strange is going on with the CSV dumps for locations and names, which worked when I ran the command manually, but appear to yield empty results when run via cron. In hindsight, this isn't too surprising since the prior issue was related to the specific ordering of command line arguments which could be different during a cron run vs a non-cron run of the same command. I will dig into this a bit further.

For RDF I'm seeing what looks like a complete set of dumps from 05/01/2016 in ``/var/www/atlantides.org/downloads/pleiades/rdf`` on 52.38.6.139 along with what appears to be complete tarball RDF archives for 05/01 and 04/27. The KML dumps also appear to be complete.

**Comment by alecpm** [comment]
All the CSV dumps now appear to be working, though I will recheck in a day to verify so that any differences between running the script directly vs from a cron job are apparent.

**Comment by paregorios** [comment]
I'm taking this issue in order to conduct review.

**Comment by paregorios** [comment]
I've invested about 3 hours today in working to verify the dump files match (but for changes made on production since content was last replicated to staging). That's all I'll be able to invest today. Here is the current status:

- RDF dumps and KML look superficially OK, but I have not closely diffed them yet
- CSV places dump is OK in detail. There are changes due to floating point management, but these appear non-destructive (and better). All other changes appear to derive from recent content changes on production
- Production CSV location dumps have fields (avgRating, numRatings) that do not appear in the staging equivalents. This is expected; however, it blows up `csvdiff` and the first workaround I tried unexpectedly and silently introduced other problems. I'll have to back up and strip those columns from the production CSV before I can move forward with more detailed testing.
- I have not had a chance to check CSV names dumps. I suspect they will have the same content ratings differences I encountered in the CSV location dumps.

**Comment by alecpm** [comment]
If you'd like I can add back the ratings field with empty values for both locations and names.

**Comment by alecpm** [comment]
On second thought, that won't help much since we're talking about line diffs for a format where each record is a single line. So nevermind.

**Comment by paregorios** [comment]
So, for reference, here are the things I was doing to test the CSV files. 

I set up a virtual environment with python 3 and the csvdiff tool. Issuing a command like the following got me a json file describing the differences:

```
csvdiff -o csv-places-diff.json uid production/csv/pleiades-places-latest.csv staging/csv/pleiades-places-latest.csv 
```

Then I fired up the python interpreter and ran the following:

```
difffile = 'csv-places-diff.json'
import json
with open(difffile) as f:
    diff = json.load(f)

affected = []
for changed in diff['changed']:
    affected.extend(changed['fields'].keys())

affected = list(set(affected))
print ("number of keys affected: {0}".format(len(affected)))
affected = {}
for changed in diff['changed']:
    for k,v in changed['fields'].items():
        if k in affected.keys():
            affected[k].append(v)
        else:
            affected[k] = [v, ]

ss = []
for k,v in affected.items():
    ss.append((k, len(v)))

print(ss)
ss.sort(key=lambda tup: tup[1])
print ("number of lines in which each key is affected:")
for s in ss:
    print ("'{0}': {1}".format(s[0], s[1]))
```

That provided some more useful information than just

```
csvdiff --style=summary production/csv/pleiades-places-latest.csv staging/csv/pleiades-places-latest.csv
```

And still in the python interpreter one can then do things like this to see whether or not the changes amount to anything important:

```
for item in affected['description']:
    print(">>> {0}".format(item))
````

**Comment by alecpm** [comment]
Great! Didn't know about csvdiff. Let me know if you'd like any output changes.
