### ISSUE TITLE
adjust reprPoint calculations to be aware of connection types - 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#316]
Right now [the representative point calculations for places](https://github.com/isawnyu/pleiades-geographer/blob/698ace62ac4b61285aec0f7795dd0a483072118a/pleiades/geographer/geo.py#L518) appear to treat all connections as having equal value (in the absence of precise locations) in centroid calculation. With the recent introduction of connection types, we should revisit the logic so that certain connection types are given special treatment. 

Containment and coincidence relationships like "part of (regional)," "part of (administrative)," "at," and "on" can probably work in a manner similar to present, but values like "near," "bounds," "flows into" and the like should probably not make use of extent centroids (maybe shortest distance?). Some connection types might need to be ignored entirely.

**Comment by paregorios** [comment]
priority:high because the current algorithm sometimes create wildly misleading representative points, ergo data corruption.

**Comment by paregorios** [comment]
regarding storify: we need a first stab at the logic of comparison if we're going to estimate this. Assigning to me for same.

**Comment by paregorios** [comment]
Migrating comments by @rmhorne from #355, which is being closed as duplicate. Some suggestions on weight:

> It might be a good idea to weight the different types of connections differently for generating a representative point. For instance "borders" and "is near / close / etc" should be more heavily weighted than "part of". Some connection types, like "allied to", (especially if we expand the connection types) should be excluded from representative points altogether, and perhaps excluded from the map as well.

**Comment by paregorios** [comment]
blocker for #354

**Comment by paregorios** [comment]
Let's try to use the following cascade of heuristics to get a better centroid calculation on the basis of connections.

- if ThisPlace has published Location(s) that do not derive from BAtlas, TAVO, or DARMC; then:
    - use only those Location(s) geometries
- elif ThisPlace has inbound Connections@type=[part_of_physical,connection,at,on]; then:
    - use only inbound Connections@type=[part_of_physical,connection,at,on]
- elif ThisPlace has inbound Connections@type=[part_of_regional,part_of_analytical]; then:
    - use only inbound Connections@type=[part_of_regional,part_of_analytical]
- elif ThisPlace has inbound Connections@type=[near,intersects,bounds,flows_into,route_next,abuts,communicates]; then:
    - use only inbound Connections@type=[near,intersects,bounds,flows_into,route_next,abuts,communicates]
- elif ThisPlace has inbound Connections@type=[member,dependent]; then:
    - use only inbound Connections@type=[member,dependent]
- else:
    - use all inbound and outbound connections of any type

**Comment by MatthewWilkes** [comment]
I think that between:

* if ThisPlace has published Location(s) that do not derive from BAtlas, TAVO, or DARMC; then:
  * use only those Location(s) geometries
* elif ThisPlace has inbound Connections@type=[part_of_physical,connection,at,on]; then:
  * use only inbound Connections@type=[part_of_physical,connection,at,on]

There should be use any other published location. Is that right, @paregorios ?

**Comment by paregorios** [comment]
@MatthewWilkes I would prefer that we take the centroid of inbound connections __before__ we consider BAtlas, TAVO, or DARMC locations. This is because BAtlas and TAVO locations are map grid square bounding boxes (on the order of 0.5x0.5 degrees in size, or larger) and because DARMC coordinates have horizontal precision on the order of +/- 2km with a significantly large sigma for horizontal accuracy due to other factors in the data creation and management process.

**Comment by paregorios** [comment]
Perhaps add a clause for these locations, but add it last, if there are no connections at all.

**Comment by paregorios** [comment]
so:

```
...
- elif ThisPlace has inbound Connections@type=[member,dependent]; then:
    - use only inbound Connections@type=[member,dependent]
- elif ThisPlace has any inbound or outbound connections at all:
    - use all inbound and outbound connections of any type
- elif ThisPlace has any DARMC Locations:
    - use all DARMC Locations
- elif ThisPlace has any Locations:
    - use all Locations
- else:
    - punt
```

**Comment by MatthewWilkes** [comment]
@paregorios Okay! I notice that we have a PositionalAccuracy type associated with locations (I'm trying to find the best way of detecting these and was hoping to avoid string matching the initialProvenance). Do you think filtering by the positional accuracy value of these types would be a good way of approaching this instead of these specific sources?

Some of them don't have accuracies set, which would be an issue, we'd probably have to fill them in?

**Comment by MatthewWilkes** [comment]
After a discussion on Slack, we've come to the following conclusions:

1) Rather than averaging co-ordinates together we should use the co-ordinate with the best PositionalAccuracy
2) The DARMC, TAVO, etc data sources should have a None for their positional accuracy. These will cause them to be discounted in the first choice of the heuristic. The last choice will be to use published locations with an undefined positional accuracy. We will continue to only use published precise locations, not rough locations.
3) We have discussed the benefits of `centroid` and `representative_point` for calculating the representative point and will continue to use centroid. This seems the most useful value for users and is guaranteed to be consistent given the same data input.

**Comment by MatthewWilkes** [comment]
Okay, so, combining this with the existing code, I have the following heuristic:

* if ThisPlace has published Location(s) that are precise
    * use the centroid of the location with the best LocationAccuracy and mark as *precise*
* elif ThisPlace has inbound Connections@type=[part_of_physical,connection,at,on] which have a precise location; then:
    * use the average of the centroids of these connections and mark as *related*
* elif ThisPlace has inbound Connections@type=[part_of_regional,part_of_analytical] which have a precise location; then:
    * use the average of the centroids of these connections and mark as *related*
* elif ThisPlace has inbound **or outbound** Connections@type=[near,intersects,bounds,flows_into,route_next,abuts,communicates] which have a precise location; then:
    * use the average of the centroids of these connections and mark as *related*
* elif ThisPlace has inbound Connections@type=[member,dependent] which have a precise location; then:
    * use the average of the centroids of these connections and mark as *related*
* elif ThisPlace has any Connections of any type or direction which have a precise location:
    * use the average of all centroids of these connections and mark as *related*
* elif ThisPlace has published Location(s) that are imprecise (grid squares):
    * use the average of all centroids and mark as *rough*
* elif ThisPlace has any Connections of any type or direction whose locations are imprecise (grid squares):
    * use the average of all centroids and mark as *rough*
* else:
    * Mark as *unlocated*

**Comment by MatthewWilkes** [comment]
Code is in https://github.com/isawnyu/pleiades-geographer/tree/tickets/316 and deployed to staging

**Comment by paregorios** [comment]
I made a mistake in the pseudocode. Two changes are requested:

## 1. In the first "elif" clause, where we read:

> ... ThisPlace has inbound Connections@type=[part_of_physical,connection,at,on] which ...

we should change the connections types list to:

```
[part_of_physical,at,on]
```

(i.e., get rid of plain "connection")

## 2. in the second "elif" clause, where we read:

> ... ThisPlace has inbound Connections@type=[part_of_regional,part_of_analytical] which ...

we should change the connections types list to:

```
[part_of_regional,part_of_analytical,part_of_admin]
```

(i.e., add a third term "part_of_admin").

**Comment by cguardia** [comment]
@paregorios I deployed the latest changes to staging.

**Comment by paregorios** [comment]
@cguardia on staging, I'm getting a traceback for ```/places/226577``` that I think may be related to this code change. [The corresponding page on production](https://pleiades.stoa.org/places/226577) runs fine. Here's the traceback:

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.CMFCore.FSPageTemplate, line 237, in _exec
    Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
    Module Products.PageTemplates.PageTemplate, line 87, in pt_render
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Warning: Macro expansion failed
    Warning: <type 'exceptions.KeyError'>: 'macro'
    Module zope.pagetemplate.pagetemplate, line 240, in __call__
    Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
    Module newrelic.api.function_trace, line 112, in literal_wrapper
    Module zope.tal.talinterpreter, line 271, in __call__
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 858, in do_defineMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 946, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 858, in do_defineMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
    Module zope.tales.tales, line 696, in evaluate
    URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
    Line 95, Column 4
    Expression: <PathExpr standard:u'context/@@where'>
    Names:

    {'container': <Place at /plone/places/226577>,
     'context': <Place at /plone/places/226577>,
     'default': <object object at 0x7f1819e6a7c0>,
     'here': <Place at /plone/places/226577>,
     'loop': {},
     'nothing': None,
     'options': {'args': ()},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f17fc404350>,
     'request': <HTTPRequest, URL=https://pleiades.jazkarta.com/places/226577/base_view>,
     'root': <Application at >,
     'template': <FSPageTemplate at /plone/places/226577/base_view>,
     'traverse_subpath': [],
     'user': <PloneUser 'thomase'>}

    Module zope.tales.expressions, line 217, in __call__
    Module Products.PageTemplates.Expressions, line 155, in _eval
    Module Products.PageTemplates.Expressions, line 117, in render
    Module pleiades.geographer.views, line 9, in __call__
    Module pleiades.geographer.geo, line 639, in coords
    Module plone.memoize.instance, line 51, in memogetter
    Module pleiades.geographer.geo, line 566, in reprPoint
    Module pleiades.geographer.geo, line 410, in preciseGeoms
    Module pleiades.geographer.geo, line 565, in <lambda>

AttributeError: 'NoneType' object has no attribute 'value' 
```

**Comment by paregorios** [comment]
Still seeing this traceback on pleiades.jazkarta.com, even after the branch synchronizations yesterday. For example https://pleiades.jazkarta.com/places/658378

**Comment by cguardia** [comment]
I put in a fix for this on staging. Now you should be able to review.

**Comment by paregorios** [comment]
Please merge to master and close this ticket at resolved.

I see several cases that are doing what I expect. E.g., 

- https://pleiades.jazkarta.com/places/231467659
- https://pleiades.jazkarta.com/places/530871
- https://pleiades.jazkarta.com/places/638965

**Comment by cguardia** [comment]
Merged to master.
