### ISSUE TITLE
Topics show too many tabs

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#63]
![screen shot 2016-03-07 at 11 11 54 am](https://cloud.githubusercontent.com/assets/49014/13580075/70f3c564-e455-11e5-8ba4-c206f8c0a8cf.png)

We should merge the Subfolders and Subtopics tabs, remove the Properties tab, remove the History tab (Plone moved it to a link in the byline) and remove the extra Sharing tab.

**Comment by davisagli** [comment]
Fixed

**Comment by paregorios** [comment]
I'm still seeing the "history" tab and the doubled "sharing" tab (one of which throws an error on click). 

![tabs](https://cloud.githubusercontent.com/assets/263285/13606185/a955b3a2-e510-11e5-8a94-4081d2788084.jpg)

**Comment by davisagli** [comment]
Fixed
